# Generated by Django 3.2.8 on 2022-07-06 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('categroy', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=30)),
                ('is_finished', models.BooleanField(default=False)),
                ('info', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
