# Generated by Django 3.2.8 on 2022-07-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categroy',
            new_name='category',
        ),
    ]
